"""Initial Sprint 1 schema.

Revision ID: 20260914_01
Revises: None
"""

from collections.abc import Sequence

from alembic import op

# This initial bootstrap is intentionally tied to the model snapshot in this commit. Before any
# model is changed, replace this create_all bootstrap with the autogenerated static operations;
# subsequent revisions must always contain static operations and never import live metadata.
from marketingiq.domain.models import Base

revision: str = "20260914_01"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
